version: 2
jobs:
    build:
        docker:
            - image: circleci/node:carbon-browsers

        working_directory: ~/repo

        steps:
            - checkout
            - run: make build
    deploy:
        docker:
            - image: circleci/node:carbon-browsers
        steps:
            - checkout
            - run: make deploy
workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
