version: 2
jobs:
    build:
        docker:
            - image: circleci/node:carbon-browsers

        working_directory: ~/repo

        steps:
            - checkout
            - run: make install
